import Head from 'next/head'
import Image from 'next/image';
import CityButton from '../components/CityButton';

import styles from '../styles/Home.module.css'

export default function Home() {

  //Use Effect Will Grab the Cities and store in state. Then we grab cities and render 


  return (
    <div className={styles.container}>
      <Head>
        <title>wtw?</title>
        <meta name="pls hr me" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <h2>Hello</h2>

      <CityButton/>
    </div>
  )
}
